PANDAS ASSIGNMENT

In [2]:
import pandas as pd

Series

In [3]:
marks = pd.Series([78, 85, 90, 67, 88])
print(marks)

0    78
1    85
2    90
3    67
4    88
dtype: int64

Dataframe

In [ ]:
data = {
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [20, 21, 19],
    "Marks": [85, 92, 78]
}

df = pd.DataFrame(data)
print(df)

Reading a CSV(Comma Seperated Values) File

In [12]:
df = pd.read_csv("student.csv")
print(df)

    ID     Name  Age  Department  Math  Science  English  Attendance
0    1      Ram   20          IT  80.0     85.0     78.0        92.0
1    2     Sita   21       Civil  92.0     90.0     88.0        95.0
2    3     Hari   19  Mechanical  75.0     70.0     80.0        88.0
3    4     Gita   22          IT  95.0     98.0     94.0        97.0
4    5    Shyam   20       Civil  88.0     82.0     85.0        90.0
5    6     Rita   21  Electrical  76.0     79.0     81.0        85.0
6    7   Bikash   23  Mechanical  69.0     72.0     74.0        80.0
7    8    Anita   20          IT  84.0     89.0     87.0        93.0
8    9    Sabin   22       Civil  91.0     87.0     90.0        94.0
9   10    Pooja   19  Electrical  73.0     75.0     77.0        82.0
10  11    Rohan   21          IT  86.0     88.0     84.0        91.0
11  12    Kiran   20  Mechanical  78.0     76.0     79.0        86.0
12  13    Nisha   22       Civil  94.0     91.0     93.0        98.0
13  14    Aarav   19  Electrical  65.0     68.0     70.0        78.0
14  15  Prakash   23  Mechanical  82.0     84.0     80.0        89.0
15  16    Sneha   20          IT  89.0     92.0     91.0        96.0
16  17    Suman   21       Civil  77.0      NaN     75.0        87.0
17  18   Alisha   20  Electrical   NaN     80.0     83.0        90.0
18  19   Dipesh   22  Mechanical  90.0     86.0      NaN        92.0
19  20   Manish   21          IT  81.0     83.0     82.0         NaN

Dataframe presentation

In [15]:
print("\nFirst 5 rows of the DataFrame:")
print(df.head())
print("\n\nLast 5 rows of the DataFrame:")    
print(df.tail())
print("\n\nRandom sample of the DataFrame:")
print(df.sample())
print("\n\nDataFrame information:")
df.info()  
print("\n\nStatistical summary of the DataFrame:")
df.describe()

First 5 rows of the DataFrame:
   ID   Name  Age  Department  Math  Science  English  Attendance
0   1    Ram   20          IT  80.0     85.0     78.0        92.0
1   2   Sita   21       Civil  92.0     90.0     88.0        95.0
2   3   Hari   19  Mechanical  75.0     70.0     80.0        88.0
3   4   Gita   22          IT  95.0     98.0     94.0        97.0
4   5  Shyam   20       Civil  88.0     82.0     85.0        90.0


Last 5 rows of the DataFrame:
    ID    Name  Age  Department  Math  Science  English  Attendance
15  16   Sneha   20          IT  89.0     92.0     91.0        96.0
16  17   Suman   21       Civil  77.0      NaN     75.0        87.0
17  18  Alisha   20  Electrical   NaN     80.0     83.0        90.0
18  19  Dipesh   22  Mechanical  90.0     86.0      NaN        92.0
19  20  Manish   21          IT  81.0     83.0     82.0         NaN


Random sample of the DataFrame:
   ID    Name  Age  Department  Math  Science  English  Attendance
6   7  Bikash   23  Mechanical  69.0     72.0     74.0        80.0


DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Department  20 non-null     object
 4   Math        19 non-null     float64
 5   Science     19 non-null     float64
 6   English     19 non-null     float64
 7   Attendance  19 non-null     float64
dtypes: float64(4), int64(2), object(2)
memory usage: 1.4+ KB


Statistical summary of the DataFrame:

             ID        Age       Math    Science    English  Attendance
count  20.00000  20.000000  19.000000  19.000000  19.000000   19.000000
mean   10.50000  20.800000  82.368421  82.894737  82.684211   89.631579
std     5.91608   1.239694   8.597225   8.040831   6.633690    5.619515
min     1.00000  19.000000  65.000000  68.000000  70.000000   78.000000
25%     5.75000  20.000000  76.500000  77.500000  78.500000   86.500000
50%    10.50000  21.000000  82.000000  84.000000  82.000000   90.000000
75%    15.25000  22.000000  89.500000  88.500000  87.500000   93.500000
max    20.00000  23.000000  95.000000  98.000000  94.000000   98.000000

In [18]:
df.shape
print(df.columns)
df.dtypes

Index(['ID', 'Name', 'Age', 'Department', 'Math', 'Science', 'English',
       'Attendance'],
      dtype='object')

ID              int64
Name           object
Age             int64
Department     object
Math          float64
Science       float64
English       float64
Attendance    float64
dtype: object

Column Selection

In [20]:
print(df[["Name", "Math"]])

       Name  Math
0       Ram  80.0
1      Sita  92.0
2      Hari  75.0
3      Gita  95.0
4     Shyam  88.0
5      Rita  76.0
6    Bikash  69.0
7     Anita  84.0
8     Sabin  91.0
9     Pooja  73.0
10    Rohan  86.0
11    Kiran  78.0
12    Nisha  94.0
13    Aarav  65.0
14  Prakash  82.0
15    Sneha  89.0
16    Suman  77.0
17   Alisha   NaN
18   Dipesh  90.0
19   Manish  81.0

In [21]:
print(df[(df["Department"] == "IT") & (df["Science"] > 85)])

    ID   Name  Age Department  Math  Science  English  Attendance
3    4   Gita   22         IT  95.0     98.0     94.0        97.0
7    8  Anita   20         IT  84.0     89.0     87.0        93.0
10  11  Rohan   21         IT  86.0     88.0     84.0        91.0
15  16  Sneha   20         IT  89.0     92.0     91.0        96.0

Null Value Check

In [ ]:
print(df.isnull().sum())
print("\n")
print(df.fillna(0))
print("\n")
df.dropna()

ID            0
Name          0
Age           0
Department    0
Math          1
Science       1
English       1
Attendance    1
dtype: int64


    ID     Name  Age  Department  Math  Science  English  Attendance
0    1      Ram   20          IT  80.0     85.0     78.0        92.0
1    2     Sita   21       Civil  92.0     90.0     88.0        95.0
2    3     Hari   19  Mechanical  75.0     70.0     80.0        88.0
3    4     Gita   22          IT  95.0     98.0     94.0        97.0
4    5    Shyam   20       Civil  88.0     82.0     85.0        90.0
5    6     Rita   21  Electrical  76.0     79.0     81.0        85.0
6    7   Bikash   23  Mechanical  69.0     72.0     74.0        80.0
7    8    Anita   20          IT  84.0     89.0     87.0        93.0
8    9    Sabin   22       Civil  91.0     87.0     90.0        94.0
9   10    Pooja   19  Electrical  73.0     75.0     77.0        82.0
10  11    Rohan   21          IT  86.0     88.0     84.0        91.0
11  12    Kiran   20  Mechanical  78.0     76.0     79.0        86.0
12  13    Nisha   22       Civil  94.0     91.0     93.0        98.0
13  14    Aarav   19  Electrical  65.0     68.0     70.0        78.0
14  15  Prakash   23  Mechanical  82.0     84.0     80.0        89.0
15  16    Sneha   20          IT  89.0     92.0     91.0        96.0
16  17    Suman   21       Civil  77.0      0.0     75.0        87.0
17  18   Alisha   20  Electrical   0.0     80.0     83.0        90.0
18  19   Dipesh   22  Mechanical  90.0     86.0      0.0        92.0
19  20   Manish   21          IT  81.0     83.0     82.0         0.0

    ID     Name  Age  Department  Math  Science  English  Attendance
0    1      Ram   20          IT  80.0     85.0     78.0        92.0
1    2     Sita   21       Civil  92.0     90.0     88.0        95.0
2    3     Hari   19  Mechanical  75.0     70.0     80.0        88.0
3    4     Gita   22          IT  95.0     98.0     94.0        97.0
4    5    Shyam   20       Civil  88.0     82.0     85.0        90.0
5    6     Rita   21  Electrical  76.0     79.0     81.0        85.0
6    7   Bikash   23  Mechanical  69.0     72.0     74.0        80.0
7    8    Anita   20          IT  84.0     89.0     87.0        93.0
8    9    Sabin   22       Civil  91.0     87.0     90.0        94.0
9   10    Pooja   19  Electrical  73.0     75.0     77.0        82.0
10  11    Rohan   21          IT  86.0     88.0     84.0        91.0
11  12    Kiran   20  Mechanical  78.0     76.0     79.0        86.0
12  13    Nisha   22       Civil  94.0     91.0     93.0        98.0
13  14    Aarav   19  Electrical  65.0     68.0     70.0        78.0
14  15  Prakash   23  Mechanical  82.0     84.0     80.0        89.0
15  16    Sneha   20          IT  89.0     92.0     91.0        96.0

Adding New Columns

In [40]:
df["Total"] = df["Math"] + df["Science"] + df["English"]

df["Percentage"] = df["Total"] / 3

print(df)

ID            0
Name          0
Age           0
Department    0
Math          1
Science       1
English       1
Attendance    1
Total         3
Percentage    1
dtype: int64